const mongoose = require('mongoose');
const University = require('../models/University');
require('dotenv').config();

const universities = [
  {
    name: "Stanford Graduate School of Business",
    location: "Stanford, CA",
    type: "MBA",
    avgGMAT: 738,
    gmatRange: { min: 690, max: 770 },
    avgGPA: 3.8,
    gpaRange: { min: 3.5, max: 4.0 },
    avgWorkExp: 4.5,
    workExpRange: { min: 3, max: 7 },
    acceptanceRate: 6.1,
    tuition: 77868,
    classSize: 410,
    ranking: 1,
    strengths: ["Tech & Innovation", "Entrepreneurship", "Leadership"],
    website: "https://www.gsb.stanford.edu"
  },
  {
    name: "Harvard Business School",
    location: "Boston, MA",
    type: "MBA",
    avgGMAT: 730,
    gmatRange: { min: 690, max: 760 },
    avgGPA: 3.7,
    gpaRange: { min: 3.4, max: 4.0 },
    avgWorkExp: 4.7,
    workExpRange: { min: 3, max: 8 },
    acceptanceRate: 11.5,
    tuition: 73440,
    classSize: 935,
    ranking: 2,
    strengths: ["General Management", "Finance", "Consulting"],
    website: "https://www.hbs.edu"
  },
  {
    name: "Wharton School - UPenn",
    location: "Philadelphia, PA",
    type: "MBA",
    avgGMAT: 733,
    gmatRange: { min: 690, max: 770 },
    avgGPA: 3.6,
    gpaRange: { min: 3.3, max: 4.0 },
    avgWorkExp: 5.0,
    workExpRange: { min: 3, max: 8 },
    acceptanceRate: 20.7,
    tuition: 78948,
    classSize: 859,
    ranking: 3,
    strengths: ["Finance", "Analytics", "Real Estate"],
    website: "https://www.wharton.upenn.edu"
  },
  {
    name: "MIT Sloan School of Management",
    location: "Cambridge, MA",
    type: "MBA",
    avgGMAT: 728,
    gmatRange: { min: 680, max: 760 },
    avgGPA: 3.6,
    gpaRange: { min: 3.3, max: 4.0 },
    avgWorkExp: 5.0,
    workExpRange: { min: 3, max: 8 },
    acceptanceRate: 14.6,
    tuition: 77168,
    classSize: 409,
    ranking: 4,
    strengths: ["Innovation", "Operations", "Entrepreneurship"],
    website: "https://mitsloan.mit.edu"
  },
  {
    name: "Columbia Business School",
    location: "New York, NY",
    type: "MBA",
    avgGMAT: 729,
    gmatRange: { min: 680, max: 760 },
    avgGPA: 3.6,
    gpaRange: { min: 3.3, max: 3.9 },
    avgWorkExp: 5.1,
    workExpRange: { min: 3, max: 9 },
    acceptanceRate: 16.4,
    tuition: 77376,
    classSize: 743,
    ranking: 5,
    strengths: ["Finance", "Investment Banking", "Private Equity"],
    website: "https://www8.gsb.columbia.edu"
  },
  {
    name: "Chicago Booth School of Business",
    location: "Chicago, IL",
    type: "MBA",
    avgGMAT: 731,
    gmatRange: { min: 690, max: 770 },
    avgGPA: 3.6,
    gpaRange: { min: 3.3, max: 3.9 },
    avgWorkExp: 5.0,
    workExpRange: { min: 3, max: 8 },
    acceptanceRate: 23.6,
    tuition: 74919,
    classSize: 593,
    ranking: 6,
    strengths: ["Economics", "Finance", "Strategy"],
    website: "https://www.chicagobooth.edu"
  },
  {
    name: "Northwestern Kellogg",
    location: "Evanston, IL",
    type: "MBA",
    avgGMAT: 728,
    gmatRange: { min: 680, max: 760 },
    avgGPA: 3.6,
    gpaRange: { min: 3.2, max: 3.9 },
    avgWorkExp: 5.0,
    workExpRange: { min: 3, max: 8 },
    acceptanceRate: 23.2,
    tuition: 76992,
    classSize: 480,
    ranking: 7,
    strengths: ["Marketing", "Leadership", "Social Impact"],
    website: "https://www.kellogg.northwestern.edu"
  },
  {
    name: "UC Berkeley Haas",
    location: "Berkeley, CA",
    type: "MBA",
    avgGMAT: 726,
    gmatRange: { min: 680, max: 760 },
    avgGPA: 3.7,
    gpaRange: { min: 3.4, max: 3.9 },
    avgWorkExp: 5.0,
    workExpRange: { min: 3, max: 8 },
    acceptanceRate: 13.4,
    tuition: 68444,
    classSize: 331,
    ranking: 8,
    strengths: ["Tech", "Sustainability", "Innovation"],
    website: "https://haas.berkeley.edu"
  },
  {
    name: "Yale School of Management",
    location: "New Haven, CT",
    type: "MBA",
    avgGMAT: 723,
    gmatRange: { min: 680, max: 750 },
    avgGPA: 3.7,
    gpaRange: { min: 3.4, max: 3.9 },
    avgWorkExp: 5.1,
    workExpRange: { min: 3, max: 8 },
    acceptanceRate: 19.6,
    tuition: 74500,
    classSize: 354,
    ranking: 9,
    strengths: ["Nonprofit", "Healthcare", "Impact Investing"],
    website: "https://som.yale.edu"
  },
  {
    name: "Duke Fuqua",
    location: "Durham, NC",
    type: "MBA",
    avgGMAT: 710,
    gmatRange: { min: 660, max: 740 },
    avgGPA: 3.5,
    gpaRange: { min: 3.2, max: 3.8 },
    avgWorkExp: 5.3,
    workExpRange: { min: 3, max: 9 },
    acceptanceRate: 22.7,
    tuition: 72900,
    classSize: 440,
    ranking: 10,
    strengths: ["Team Fuqua Culture", "Healthcare", "Consulting"],
    website: "https://www.fuqua.duke.edu"
  },
  {
    name: "Dartmouth Tuck",
    location: "Hanover, NH",
    type: "MBA",
    avgGMAT: 723,
    gmatRange: { min: 680, max: 750 },
    avgGPA: 3.6,
    gpaRange: { min: 3.3, max: 3.9 },
    avgWorkExp: 5.0,
    workExpRange: { min: 3, max: 8 },
    acceptanceRate: 21.6,
    tuition: 77520,
    classSize: 286,
    ranking: 11,
    strengths: ["General Management", "Tight-knit Community", "Leadership"],
    website: "https://www.tuck.dartmouth.edu"
  },
  {
    name: "NYU Stern",
    location: "New York, NY",
    type: "MBA",
    avgGMAT: 721,
    gmatRange: { min: 670, max: 750 },
    avgGPA: 3.6,
    gpaRange: { min: 3.2, max: 3.8 },
    avgWorkExp: 5.2,
    workExpRange: { min: 3, max: 9 },
    acceptanceRate: 23.1,
    tuition: 76780,
    classSize: 406,
    ranking: 12,
    strengths: ["Finance", "Tech", "Luxury Marketing"],
    website: "https://www.stern.nyu.edu"
  },
  {
    name: "Michigan Ross",
    location: "Ann Arbor, MI",
    type: "MBA",
    avgGMAT: 716,
    gmatRange: { min: 670, max: 750 },
    avgGPA: 3.5,
    gpaRange: { min: 3.2, max: 3.8 },
    avgWorkExp: 5.3,
    workExpRange: { min: 3, max: 9 },
    acceptanceRate: 23.5,
    tuition: 71048,
    classSize: 380,
    ranking: 13,
    strengths: ["Action-based Learning", "Consulting", "Tech"],
    website: "https://michiganross.umich.edu"
  },
  {
    name: "Virginia Darden",
    location: "Charlottesville, VA",
    type: "MBA",
    avgGMAT: 713,
    gmatRange: { min: 670, max: 740 },
    avgGPA: 3.5,
    gpaRange: { min: 3.2, max: 3.8 },
    avgWorkExp: 5.5,
    workExpRange: { min: 3, max: 10 },
    acceptanceRate: 26.3,
    tuition: 72614,
    classSize: 352,
    ranking: 14,
    strengths: ["Case Method", "Consulting", "General Management"],
    website: "https://www.darden.virginia.edu"
  },
  {
    name: "Cornell Johnson",
    location: "Ithaca, NY",
    type: "MBA",
    avgGMAT: 700,
    gmatRange: { min: 650, max: 730 },
    avgGPA: 3.4,
    gpaRange: { min: 3.1, max: 3.7 },
    avgWorkExp: 5.3,
    workExpRange: { min: 3, max: 9 },
    acceptanceRate: 30.7,
    tuition: 72984,
    classSize: 283,
    ranking: 15,
    strengths: ["Immersion Learning", "Tech", "Hospitality"],
    website: "https://www.johnson.cornell.edu"
  },
  {
    name: "UCLA Anderson",
    location: "Los Angeles, CA",
    type: "MBA",
    avgGMAT: 714,
    gmatRange: { min: 670, max: 740 },
    avgGPA: 3.6,
    gpaRange: { min: 3.2, max: 3.8 },
    avgWorkExp: 5.2,
    workExpRange: { min: 3, max: 8 },
    acceptanceRate: 20.9,
    tuition: 65114,
    classSize: 360,
    ranking: 16,
    strengths: ["Entertainment", "Tech", "Entrepreneurship"],
    website: "https://www.anderson.ucla.edu"
  },
  {
    name: "Carnegie Mellon Tepper",
    location: "Pittsburgh, PA",
    type: "MBA",
    avgGMAT: 690,
    gmatRange: { min: 650, max: 730 },
    avgGPA: 3.5,
    gpaRange: { min: 3.1, max: 3.7 },
    avgWorkExp: 5.5,
    workExpRange: { min: 3, max: 10 },
    acceptanceRate: 28.3,
    tuition: 70500,
    classSize: 220,
    ranking: 17,
    strengths: ["Analytics", "Operations", "Tech"],
    website: "https://www.cmu.edu/tepper"
  },
  {
    name: "UNC Kenan-Flagler",
    location: "Chapel Hill, NC",
    type: "MBA",
    avgGMAT: 701,
    gmatRange: { min: 650, max: 730 },
    avgGPA: 3.5,
    gpaRange: { min: 3.1, max: 3.7 },
    avgWorkExp: 5.3,
    workExpRange: { min: 3, max: 9 },
    acceptanceRate: 37.6,
    tuition: 65823,
    classSize: 281,
    ranking: 18,
    strengths: ["Marketing", "Consulting", "Sustainable Enterprise"],
    website: "https://www.kenan-flagler.unc.edu"
  },
  {
    name: "UT Austin McCombs",
    location: "Austin, TX",
    type: "MBA",
    avgGMAT: 704,
    gmatRange: { min: 660, max: 730 },
    avgGPA: 3.5,
    gpaRange: { min: 3.1, max: 3.7 },
    avgWorkExp: 5.4,
    workExpRange: { min: 3, max: 10 },
    acceptanceRate: 36.1,
    tuition: 60516,
    classSize: 264,
    ranking: 19,
    strengths: ["Tech", "Entrepreneurship", "Energy"],
    website: "https://www.mccombs.utexas.edu"
  },
  {
    name: "USC Marshall",
    location: "Los Angeles, CA",
    type: "MBA",
    avgGMAT: 707,
    gmatRange: { min: 660, max: 730 },
    avgGPA: 3.4,
    gpaRange: { min: 3.1, max: 3.7 },
    avgWorkExp: 5.1,
    workExpRange: { min: 3, max: 8 },
    acceptanceRate: 25.9,
    tuition: 68592,
    classSize: 245,
    ranking: 20,
    strengths: ["Entertainment", "Entrepreneurship", "Real Estate"],
    website: "https://www.marshall.usc.edu"
  },
  {
    name: "Emory Goizueta",
    location: "Atlanta, GA",
    type: "MBA",
    avgGMAT: 690,
    gmatRange: { min: 650, max: 720 },
    avgGPA: 3.4,
    gpaRange: { min: 3.0, max: 3.7 },
    avgWorkExp: 5.2,
    workExpRange: { min: 3, max: 9 },
    acceptanceRate: 39.7,
    tuition: 67900,
    classSize: 185,
    ranking: 21,
    strengths: ["Marketing", "Consulting", "Social Enterprise"],
    website: "https://goizueta.emory.edu"
  },
  {
    name: "Washington Olin",
    location: "St. Louis, MO",
    type: "MBA",
    avgGMAT: 696,
    gmatRange: { min: 650, max: 730 },
    avgGPA: 3.5,
    gpaRange: { min: 3.1, max: 3.7 },
    avgWorkExp: 5.4,
    workExpRange: { min: 3, max: 9 },
    acceptanceRate: 32.1,
    tuition: 66500,
    classSize: 150,
    ranking: 22,
    strengths: ["Healthcare", "Supply Chain", "Finance"],
    website: "https://olin.wustl.edu"
  }
];

async function seedDatabase() {
  try {
    await mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/mba-matcher');
    console.log('Connected to MongoDB');

    // Clear existing data
    await University.deleteMany({});
    console.log('Cleared existing universities');

    // Insert new data
    await University.insertMany(universities);
    console.log(`✅ Successfully seeded ${universities.length} universities`);

    mongoose.connection.close();
  } catch (error) {
    console.error('Error seeding database:', error);
    mongoose.connection.close();
  }
}

seedDatabase();